module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- src/Main.hs
- src/TypeFamilies.hs
